definitions:
  requests.CreateBookingDetailRequest:
    properties:
      roomId:
        type: string
    required:
    - roomId
    type: object
  requests.CreateBookingRequest:
    properties:
      BookedBy:
        type: string
      bookingDetails:
        items:
          $ref: '#/definitions/requests.CreateBookingDetailRequest'
        type: array
      downPayment:
        type: integer
      endDate:
        type: string
      isTimeRulesAgree:
        type: boolean
      startDate:
        type: string
    required:
    - BookedBy
    - bookingDetails
    - downPayment
    - endDate
    - startDate
    type: object
  responses.AlertResponse:
    properties:
      code:
        type: integer
      inner_message:
        type: string
      message:
        type: string
    type: object
  responses.CommonBaseResponse:
    properties:
      alert:
        $ref: '#/definitions/responses.AlertResponse'
      data: {}
    type: object
info:
  contact: {}
paths:
  /api/cms/v1/booking/create:
    post:
      consumes:
      - application/json
      description: Booking Create
      operationId: BookingCreate
      parameters:
      - description: Bearer %
        in: header
        name: Authorization
        required: true
        type: string
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/requests.CreateBookingRequest'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.CommonBaseResponse'
      tags:
      - Booking
  /api/cms/v1/floor/create:
    post:
      consumes:
      - multipart/form-data
      description: Floor Create
      operationId: FloorCreate
      parameters:
      - description: Bearer %
        in: header
        name: Authorization
        required: true
        type: string
      - description: number
        in: formData
        name: number
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.CommonBaseResponse'
      tags:
      - Floor
  /api/cms/v1/room-price/create:
    post:
      consumes:
      - multipart/form-data
      description: RoomPrice Create
      operationId: RoomPriceCreate
      parameters:
      - description: Bearer %
        in: header
        name: Authorization
        required: true
        type: string
      - description: code
        in: formData
        name: code
        required: true
        type: string
      - description: type
        in: formData
        name: type
        required: true
        type: string
      - description: price
        in: formData
        name: price
        required: true
        type: string
      - description: floorId
        in: formData
        name: floorId
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.CommonBaseResponse'
      tags:
      - RoomPrice
  /api/cms/v1/room/availibility-room:
    get:
      consumes:
      - multipart/form-data
      description: Room Get Availibility Room
      operationId: RoomGetAvailibilityRoom
      parameters:
      - description: Bearer %
        in: header
        name: Authorization
        required: true
        type: string
      - description: startDate
        in: query
        name: startDate
        type: string
      - description: endDate
        in: query
        name: endDate
        type: string
      - description: floorNumber
        in: query
        name: floorNumber
        type: integer
      - description: roomNumber
        in: query
        name: roomNumber
        type: integer
      - description: roomTypeName
        in: query
        name: roomTypeName
        type: string
      - description: startFloorPrice
        in: query
        name: startPrice
        type: integer
      - description: endfloorPrice
        in: query
        name: endPrice
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.CommonBaseResponse'
      tags:
      - Room
  /api/cms/v1/room/create:
    post:
      consumes:
      - multipart/form-data
      description: Room Create
      operationId: RoomCreate
      parameters:
      - description: Bearer %
        in: header
        name: Authorization
        required: true
        type: string
      - description: floorId
        in: formData
        name: floorId
        required: true
        type: string
      - description: code
        in: formData
        name: code
        required: true
        type: string
      - description: number
        in: formData
        name: number
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.CommonBaseResponse'
      tags:
      - Room
  /api/cms/v1/user/create:
    post:
      consumes:
      - multipart/form-data
      description: User Create
      operationId: UserCreate
      parameters:
      - description: username
        in: formData
        name: username
        required: true
        type: string
      - description: password
        in: formData
        name: password
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.CommonBaseResponse'
      tags:
      - User
  /api/cms/v1/user/login:
    post:
      consumes:
      - multipart/form-data
      description: User Login
      operationId: UserLogin
      parameters:
      - description: username
        in: formData
        name: username
        required: true
        type: string
      - description: password
        in: formData
        name: password
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.CommonBaseResponse'
      tags:
      - User
swagger: "2.0"
