definitions:
  responses.AlertResponse:
    properties:
      code:
        type: integer
      inner_message:
        type: string
      message:
        type: string
    type: object
  responses.CommonBaseResponse:
    properties:
      alert:
        $ref: '#/definitions/responses.AlertResponse'
      data: {}
    type: object
info:
  contact: {}
paths:
  /api/cms/v1/floor/create:
    post:
      consumes:
      - multipart/form-data
      description: Floor Create
      operationId: FloorCreate
      parameters:
      - description: Bearer %
        in: header
        name: Authorization
        required: true
        type: string
      - description: number
        in: formData
        name: number
        required: true
        type: integer
      - description: roomTypeId
        in: formData
        name: roomTypeId
        type: integer
      - description: price
        in: formData
        name: price
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.CommonBaseResponse'
      tags:
      - Floor
swagger: "2.0"
