definitions:
  requests.CreateBookingDetailRequest:
    properties:
      roomId:
        type: string
    required:
    - roomId
    type: object
  requests.CreateBookingRequest:
    properties:
      bookedName:
        type: string
      bookingDetails:
        items:
          $ref: '#/definitions/requests.CreateBookingDetailRequest'
        type: array
      downPayment:
        type: integer
      endDate:
        type: string
      isTimeRulesAgree:
        type: boolean
      startDate:
        type: string
    required:
    - bookedName
    - bookingDetails
    - downPayment
    - endDate
    - startDate
    type: object
  responses.AlertResponse:
    properties:
      code:
        type: integer
      inner_message:
        type: string
      message:
        type: string
    type: object
  responses.CommonBaseResponse:
    properties:
      alert:
        $ref: '#/definitions/responses.AlertResponse'
      data: {}
    type: object
info:
  contact: {}
paths:
  /api/cms/v1/booking/create:
    post:
      consumes:
      - application/json
      description: Booking Create
      operationId: BookingCreate
      parameters:
      - description: Bearer %
        in: header
        name: Authorization
        required: true
        type: string
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/requests.CreateBookingRequest'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.CommonBaseResponse'
      tags:
      - Booking
  /api/cms/v1/floor/create:
    post:
      consumes:
      - multipart/form-data
      description: Floor Create
      operationId: FloorCreate
      parameters:
      - description: Bearer %
        in: header
        name: Authorization
        required: true
        type: string
      - description: number
        in: formData
        name: number
        required: true
        type: integer
      - description: roomTypeId
        in: formData
        name: roomTypeId
        required: true
        type: string
      - description: price
        in: formData
        name: price
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.CommonBaseResponse'
      tags:
      - Floor
  /api/cms/v1/room-type/create:
    post:
      consumes:
      - multipart/form-data
      description: RoomType Create
      operationId: RoomTypeCreate
      parameters:
      - description: Bearer %
        in: header
        name: Authorization
        required: true
        type: string
      - description: code
        in: formData
        name: code
        required: true
        type: string
      - description: name
        in: formData
        name: name
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.CommonBaseResponse'
      tags:
      - RoomType
  /api/cms/v1/room/create:
    post:
      consumes:
      - multipart/form-data
      description: Room Create
      operationId: RoomCreate
      parameters:
      - description: Bearer %
        in: header
        name: Authorization
        required: true
        type: string
      - description: floorId
        in: formData
        name: floorId
        required: true
        type: string
      - description: code
        in: formData
        name: code
        required: true
        type: string
      - description: number
        in: formData
        name: number
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.CommonBaseResponse'
      tags:
      - Room
swagger: "2.0"
